### ISSUE TITLE
github api for tags

### ISSUE THREAD

**Issue by ArtskydJ** [coreybutler/nodedistro#6]
It sounds like this module exists because https://api.github.com/repos/joyent/node/releases returns no results. But https://api.github.com/repos/joyent/node/tags does return results.

https://api.github.com/repos/npm/npm/tags and https://api.github.com/repos/npm/npm/releases return results.

Would using the github tags api relenquish the need for this module?

**Comment by coreybutler** [comment]
There are a few problems with these feeds (I tried to use them!). 

While the feeds listed provide the versions for node and npm individually, they do not address the relationship between them... i.e. there is no way to tell which version of npm corresponds its node counterpart. The only place where I have found a reliable mapping of npm --> node version is in the release notes, which (as you mentioned) don't return any results. This is why I scrape the release page instead of relying on the JSON feed. 

Additionally, the tags aren't a reliable source for available versions of node because there are often more tags than versions. Right now, the results show `works` as a version... and while those are easy enough to skip over, I have seen tags for future versions show up before a release... i.e. I wouldn't be surprised to see a tag of `v0.13.0` before there is a release.

I really wish Node would just maintain a list, but the rather terse [feedback](https://github.com/joyent/node/issues/8075) I got indicates they have no intention of doing this.
